### PR TITLE
Add director query feature

### PR DESCRIPTION
**Pull request by sdistefano**

### CODE REVIEW

**Comment by preritdas** [comment]
Can you merge my `master` into yours to remove legacy Python 3.6 support? That’ll allow the tests to run properly. Also it’d be great if you wrote a test for directors too - in tests/standalone just pick a movie, find the directors, and make sure the function outputs those directors. If not that’s alright, I’ll implement it after merging. @sdistefano

**Comment by sdistefano** [comment]
Hi @preritdas, it's done! Sorry I had not noticed there were tests.

**Comment by preritdas** [comment]
Tests are failing, I think you need “Tony Scott” instead of “Joseph Kosinski” in your tests… ;)

Also, did you consider adding `self.directors` to the `str` representation of a `Movie` object? In `movie.py`. @sdistefano

**Comment by preritdas** [comment]
Awesome! Thanks for implementing this, I'll merge and then increment `setup.py` so your changes are deployed to PyPI.

**Pull request merged**
